import datetime                              # For timestamp columns
import json                                
from sqlalchemy import (
    Column,        
    String,       
    Integer,       
    Float,        
    Boolean, 
    DateTime,  
    Text,          
)
from sqlalchemy.orm import DeclarativeBase   # Base class all models inherit from


class Base(DeclarativeBase):
    """
    The base class that all ORM models inherit from.
    This is what SQLAlchemy uses to keep track of all your table definitions.
    Alembic's env.py imports this Base to know which tables to manage.
    """
    pass


class Message(Base):
    """
    One row = one message (either from the user or the assistant).
    Used for:
      - Reconstructing conversation history for the API's /history endpoint
      - Injecting the last K messages as short-term context into the agent
      - Triggering auto-summarization when count exceeds threshol
    """

    __tablename__ = "messages"

    id = Column(Integer, primary_key=True, autoincrement=True)

    user_id = Column(String(255), nullable=False, index=True)

    session_id = Column(String(36), nullable=False, index=True)  # 36 = UUID length

    role = Column(String(20), nullable=False)

    content = Column(Text, nullable=False)

    created_at = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)

    def __repr__(self):
        """Readable string representation for debugging"""
        preview = self.content[:50] + "..." if len(self.content) > 50 else self.content
        return f"<Message id={self.id} user={self.user_id} role={self.role} '{preview}'>"


class UserFact(Base):
    """
    One row = one fact about a user (key-value pair).
    Think of this as a user's CRM profile built automatically from conversations.
    """
    __tablename__ = "user_facts"

    id = Column(Integer, primary_key=True, autoincrement=True)

    user_id = Column(String(255), nullable=False, index=True)

    fact_key = Column(String(100), nullable=False)

    fact_value = Column(Text, nullable=False)

    confidence = Column(Float, default=1.0)

    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)

    def __repr__(self):
        return f"<UserFact user={self.user_id} {self.fact_key}='{self.fact_value}'>"


class Summary(Base):
    """
    One row = one compressed summary of a user's conversation history.
    Generated by the model when message count exceeds the threshold.

    """
    __tablename__ = "summaries"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(String(255), nullable=False, index=True)

    session_id = Column(String(36), nullable=False)

    summary_text = Column(Text, nullable=False)

    message_count_covered = Column(Integer, default=0)

    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    def __repr__(self):
        preview = self.summary_text[:60] + "..." if len(self.summary_text) > 60 else self.summary_text
        return f"<Summary user={self.user_id} '{preview}'>"


class Session(Base):
    """
    One row = one conversation session (one POST /chat call).
    Stores metadata about when a session happened and how many messages it had.
    This powers the aggregated eval stats in GET /chat/{user_id}/evals.
    """
    __tablename__ = "sessions"

    id = Column(String(36), primary_key=True)  # UUID string, e.g., "550e8400-e29b..."

    user_id = Column(String(255), nullable=False, index=True)
    started_at = Column(DateTime, default=datetime.datetime.utcnow)
    ended_at = Column(DateTime, nullable=True)  # Null until the request completes
    message_count = Column(Integer, default=0)

    def __repr__(self):
        return f"<Session id={self.id[:8]}... user={self.user_id}>"


class Flag(Base):
    """
    One row = one escalation event (agent requested human review).
    This is the "human-in-the-loop" mechanism.

    """
    __tablename__ = "flags"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(String(255), nullable=False, index=True)
    session_id = Column(String(36), nullable=False)

    reason = Column(Text, nullable=False)

    confidence = Column(Float, nullable=True)

    resolved = Column(Boolean, default=False)

    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    def __repr__(self):
        return f"<Flag user={self.user_id} reason='{self.reason[:40]}' resolved={self.resolved}>"


class Eval(Base):
    """
    One row = one self-evaluation result for one agent response.
    Every single response gets an eval, which is logged here permanently.

    The three scores (0.0 to 1.0):
      - groundedness: Is the response backed by actual catalog data?
      - relevance:    Does the response actually answer the user's question?
      - confidence:   Overall quality score. If < threshold -> flagged.

    These scores are generated by a second the model call in eval_service.py.
    They are "LLM self-scores" — imperfect but far better than random numbers.
    """
    __tablename__ = "evals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(String(255), nullable=False, index=True)
    session_id = Column(String(36), nullable=False, index=True)

    groundedness = Column(Float, nullable=False)  # Factual accuracy vs catalog
    relevance = Column(Float, nullable=False)      # Relevance to user's question
    confidence = Column(Float, nullable=False)     # Overall confidence

    flagged = Column(Boolean, default=False)

    reasoning = Column(Text, nullable=True)

    tools_called = Column(Text, default="[]")

    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    def get_tools_called_list(self) -> list:
        """
        Helper to deserialize the JSON string back to a Python list.
        Usage: eval.get_tools_called_list()  ->  ["search_catalog", "get_user_memory"]
        """
        try:
            return json.loads(self.tools_called)
        except (json.JSONDecodeError, TypeError):
            return []

    def __repr__(self):
        return (
            f"<Eval user={self.user_id} "
            f"ground={self.groundedness:.2f} "
            f"rel={self.relevance:.2f} "
            f"conf={self.confidence:.2f} "
            f"flagged={self.flagged}>"
        )
