
from pydantic import BaseModel, Field
from typing import Optional
import datetime



class ChatRequest(BaseModel):
    """
    The request body for POST /chat/{user_id}.

    Example valid JSON:
        {"message": "What's the Enterprise pricing?"}

    Example invalid JSON (will return 422 error):
        {"message": 12345}   ← message must be a string, not an integer
        {}                   ← message is required
    """

    message: str = Field(
        ...,   # required
        min_length=1,        # Can't send an empty message
        max_length=5000,     # Reasonable limit to avoid abuse
        description="The user's message to the sales assistant",
        json_schema_extra={"example": "What's the difference between Growth and Enterprise?"}
    )



class EvalBlock(BaseModel):
    """
    The self-evaluation block included in every /chat response.
    Generated by the eval service after every agent response.

    All scores are 0.0 to 1.0 (higher = better).
    """

    groundedness: float = Field(
        ...,
        ge=0.0, le=1.0,  # ge = >=, le = <=
        description=(
            "How well grounded the response is in the product catalog. "
            "High (0.9+) = directly sourced from catalog. "
            "Low (<0.5) = agent may have guessed or hallucinated."
        )
    )

    relevance: float = Field(
        ...,
        ge=0.0, le=1.0,
        description=(
            "How relevant the response is to the user's actual question. "
            "High = directly answers what was asked. "
            "Low = agent went off-topic or gave a generic answer."
        )
    )

    confidence: float = Field(
        ...,
        ge=0.0, le=1.0,
        description=(
            "Overall confidence in the response quality. "
            "If below EVAL_CONFIDENCE_THRESHOLD (default 0.7), flagged=True."
        )
    )

    flagged: bool = Field(
        ...,
        description=(
            "True if confidence is below threshold OR agent called flag_for_human. "
            "Flagged responses are logged for human review."
        )
    )

    reasoning: str = Field(
        ...,
        description="the model's own explanation for why it gave these scores"
    )


class ChatResponse(BaseModel):
    """
    The full response body for POST /chat/{user_id}.

    This is the main data structure the frontend receives on every chat turn.
    The eval block is always present — never optional.
    """

    response: str = Field(
        ...,
        description="The agent's text response to the user's message"
    )

    eval: EvalBlock = Field(
        ...,
        description="Self-evaluation scores for this response (always present)"
    )

    tools_called: list[str] = Field(
        default=[],
        description=(
            "Names of the tools that were actually called to generate this response. "
            "e.g., ['search_catalog', 'get_user_memory']"
        )
    )

    session_id: str = Field(
        ...,
        description="UUID of this conversation session (use for debugging/tracing)"
    )


class MessageRecord(BaseModel):
    """
    One message in the conversation history.
    Used in the response for GET /chat/{user_id}/history.
    """

    id: int
    user_id: str
    session_id: str
    role: str = Field(..., description="'user' or 'assistant'")
    content: str
    created_at: datetime.datetime

    class Config:
        from_attributes = True


class HistoryResponse(BaseModel):
    """
    Response body for GET /chat/{user_id}/history.
    Returns the full conversation history across ALL sessions.
    """

    user_id: str
    total_messages: int = Field(..., description="Total number of messages in history")
    messages: list[MessageRecord] = Field(..., description="All messages in chronological order")


class UserFactRecord(BaseModel):
    """
    One extracted long-term fact about a user.
    Included in the history response for context.
    """
    fact_key: str
    fact_value: str
    confidence: float
    updated_at: Optional[datetime.datetime] = None

    class Config:
        from_attributes = True


class EvalRecord(BaseModel):
    """
    One eval record from the database.
    Used in the GET /chat/{user_id}/evals response.
    """
    session_id: str
    groundedness: float
    relevance: float
    confidence: float
    flagged: bool
    reasoning: Optional[str]
    tools_called: list[str] = []
    created_at: datetime.datetime

    class Config:
        from_attributes = True


class EvalAggregateResponse(BaseModel):
    """
    Response body for GET /chat/{user_id}/evals (bonus endpoint).

    Aggregates all eval scores for a user across all sessions.
    Useful for a dashboard showing response quality over time.
    """

    user_id: str
    total_responses: int = Field(..., description="Total number of evaluated responses")
    avg_groundedness: float = Field(..., description="Average groundedness score across all responses")
    avg_relevance: float = Field(..., description="Average relevance score across all responses")
    avg_confidence: float = Field(..., description="Average confidence score across all responses")
    pct_flagged: float = Field(..., description="Percentage of responses that were flagged (0.0 to 100.0)")
    total_flagged: int = Field(..., description="Number of responses that were flagged for review")
    recent_evals: list[EvalRecord] = Field(..., description="Last 10 eval records (most recent first)")


class MemoryDeleteResponse(BaseModel):
    """
    Response body for DELETE /chat/{user_id}/memory.
    Confirms what was deleted (GDPR compliance).
    """

    user_id: str
    deleted: dict = Field(
        ...,
        description="Count of deleted records per table",
        json_schema_extra={"example": {
            "messages": 42,
            "user_facts": 8,
            "summaries": 2,
            "sessions": 5,
            "evals": 42,
            "flags": 1
        }}
    )
    message: str = Field(default="All memory data for this user has been permanently deleted.")


class CatalogResponse(BaseModel):
    """
    Response body for GET /catalog.
    Returns the raw product catalog JSON.
    """
    catalog: dict = Field(..., description="The full product catalog JSON")


class HealthResponse(BaseModel):
    """
    Response body for GET /health.
    Used by Railway and monitoring tools to check if the service is alive.
    """
    status: str = Field(..., description="'healthy' or 'degraded'")
    database: str = Field(..., description="'connected' or 'error'")
    catalog: str = Field(..., description="'loaded' or 'error'")
    vector_store: str = Field(..., description="'initialized' or 'error'")
    version: str = Field(default="1.0.0")
